import {
  HomeIcon,
  LayoutDashboardIcon,
  CompassIcon,
  NavigationIcon,
  FolderKanbanIcon,
  CheckSquareIcon,
  ClipboardListIcon,
  BriefcaseIcon,
  UsersIcon,
  UserIcon,
  Building2Icon,
  ShieldCheckIcon,
  ShieldIcon,
  KeyIcon,
  LockIcon,
  EyeIcon,
  ListIcon,
  GridIcon,
  ColumnsIcon,
  LayersIcon,
  SettingsIcon,
  WrenchIcon,
  SlidersHorizontalIcon,
  CpuIcon,
  PowerIcon,
  ScrollTextIcon,
  ActivityIcon,
  MonitorIcon,
  BarChart3Icon,
  PieChartIcon,
  TrendingUpIcon,
  FolderIcon,
  FileIcon,
  FileTextIcon,
  BookOpenIcon,
  PaperclipIcon,
  DatabaseIcon,
  ServerIcon,
  CloudIcon,
  BoxIcon,
  PackageIcon,
  InboxIcon,
  MailIcon,
  MessageSquareIcon,
  BellIcon,
  SendIcon,
  PhoneIcon,
  ImageIcon,
  VideoIcon,
  MusicIcon,
  VolumeIcon,
  ShoppingCartIcon,
  CreditCardIcon,
  DollarSignIcon,
  PercentIcon,
  TruckIcon,
  GiftIcon,
  SearchIcon,
  FilterIcon,
  UploadIcon,
  DownloadIcon,
  LinkIcon,
  RefreshCwIcon,
  ScissorsIcon,
  ShuffleIcon,
  CodeIcon,
  TerminalIcon,
  GitBranchIcon,
  HashIcon,
  GlobeIcon,
  MapPinIcon,
  WifiIcon,
  RadioIcon,
  SmartphoneIcon,
  PrinterIcon,
  TagIcon,
  FlagIcon,
  StarIcon,
  HeartIcon,
  ThumbsUpIcon,
  AwardIcon,
  AlertTriangleIcon,
  InfoIcon,
  HelpCircleIcon,
  ZapIcon,
  CalendarIcon,
  RocketIcon,
  FeatherIcon,
  CircleIcon,
  SquareIcon,
} from 'lucide-react';

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // 常用/导航
  Home: HomeIcon,
  LayoutDashboard: LayoutDashboardIcon,
  Compass: CompassIcon,
  Navigation: NavigationIcon,
  // 项目/任务
  FolderKanban: FolderKanbanIcon,
  CheckSquare: CheckSquareIcon,
  ClipboardList: ClipboardListIcon,
  Briefcase: BriefcaseIcon,
  // 用户/组织
  Users: UsersIcon,
  UsersIcon: UsersIcon,
  User: UserIcon,
  Building2: Building2Icon,
  Building2Icon: Building2Icon,
  // 权限/安全
  ShieldCheck: ShieldCheckIcon,
  ShieldCheckIcon: ShieldCheckIcon,
  Shield: ShieldIcon,
  Key: KeyIcon,
  KeyIcon: KeyIcon,
  Lock: LockIcon,
  Eye: EyeIcon,
  // 菜单/列表
  List: ListIcon,
  ListIcon: ListIcon,
  Grid: GridIcon,
  Columns: ColumnsIcon,
  Layers: LayersIcon,
  // 系统/设置
  Settings: SettingsIcon,
  SettingsIcon: SettingsIcon,
  Wrench: WrenchIcon,
  WrenchIcon: WrenchIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Cpu: CpuIcon,
  Power: PowerIcon,
  // 日志/监控
  ScrollText: ScrollTextIcon,
  ScrollTextIcon: ScrollTextIcon,
  Activity: ActivityIcon,
  ActivityIcon: ActivityIcon,
  Monitor: MonitorIcon,
  MonitorIcon: MonitorIcon,
  BarChart3: BarChart3Icon,
  BarChart3Icon: BarChart3Icon,
  PieChart: PieChartIcon,
  TrendingUp: TrendingUpIcon,
  // 文件/文档
  Folder: FolderIcon,
  File: FileIcon,
  FileText: FileTextIcon,
  FileTextIcon: FileTextIcon,
  BookOpen: BookOpenIcon,
  BookOpenIcon: BookOpenIcon,
  Paperclip: PaperclipIcon,
  // 数据/存储
  Database: DatabaseIcon,
  DatabaseIcon: DatabaseIcon,
  Server: ServerIcon,
  ServerIcon: ServerIcon,
  Cloud: CloudIcon,
  CloudIcon: CloudIcon,
  Box: BoxIcon,
  Package: PackageIcon,
  PackageIcon: PackageIcon,
  Inbox: InboxIcon,
  // 通信/消息
  Mail: MailIcon,
  MailIcon: MailIcon,
  MessageSquare: MessageSquareIcon,
  Bell: BellIcon,
  BellIcon: BellIcon,
  Send: SendIcon,
  Phone: PhoneIcon,
  // 媒体
  Image: ImageIcon,
  Video: VideoIcon,
  Music: MusicIcon,
  Volume: VolumeIcon,
  // 电商/财务
  ShoppingCart: ShoppingCartIcon,
  ShoppingCartIcon: ShoppingCartIcon,
  CreditCard: CreditCardIcon,
  CreditCardIcon: CreditCardIcon,
  DollarSign: DollarSignIcon,
  Percent: PercentIcon,
  Truck: TruckIcon,
  Gift: GiftIcon,
  // 工具/操作
  Search: SearchIcon,
  Filter: FilterIcon,
  Upload: UploadIcon,
  Download: DownloadIcon,
  Link: LinkIcon,
  RefreshCw: RefreshCwIcon,
  Scissors: ScissorsIcon,
  Shuffle: ShuffleIcon,
  // 开发
  Code: CodeIcon,
  CodeIcon: CodeIcon,
  Terminal: TerminalIcon,
  GitBranch: GitBranchIcon,
  Hash: HashIcon,
  // 地理/网络
  Globe: GlobeIcon,
  GlobeIcon: GlobeIcon,
  MapPin: MapPinIcon,
  MapPinIcon: MapPinIcon,
  Wifi: WifiIcon,
  Radio: RadioIcon,
  // 设备
  Smartphone: SmartphoneIcon,
  Printer: PrinterIcon,
  // 状态/标记
  Tag: TagIcon,
  TagIcon: TagIcon,
  Flag: FlagIcon,
  FlagIcon: FlagIcon,
  Star: StarIcon,
  StarIcon: StarIcon,
  Heart: HeartIcon,
  HeartIcon: HeartIcon,
  ThumbsUp: ThumbsUpIcon,
  Award: AwardIcon,
  // 提示/信息
  AlertTriangle: AlertTriangleIcon,
  Info: InfoIcon,
  HelpCircle: HelpCircleIcon,
  Zap: ZapIcon,
  ZapIcon: ZapIcon,
  // 其他
  Calendar: CalendarIcon,
  CalendarIcon: CalendarIcon,
  Rocket: RocketIcon,
  RocketIcon: RocketIcon,
  Feather: FeatherIcon,
  Circle: CircleIcon,
  Square: SquareIcon,
};

/** 过滤掉 Icon 后缀别名的图标名称列表，供选择器使用 */
export const iconOptions = Object.entries(iconMap)
  .filter(([name]) => !name.endsWith('Icon'))
  .map(([name]) => name);
